# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

buildMatrix <- function(conceptData, observationPeriodReference, weights, windowSize, context, numberOfConcepts) {
    .Call('_GloVeHd_buildMatrix', PACKAGE = 'GloVeHd', conceptData, observationPeriodReference, weights, windowSize, context, numberOfConcepts)
}

